services:

  archivist-agent:
    build:
      context: ./../containers_base/container_base_agent
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./agent:/app/code/agent
      - ./../../../aigency:/app/code/aigency
    env_file:
      - .env
    restart: unless-stopped
    command: >
      sh -c "pip install watchdog && \
             export PYTHONPATH=/app/code:/app/code/agent && \
             watchmedo auto-restart --directory=/app/code --patterns='*.py;*.yaml;*.yml' --recursive -- python /app/code/agent/__main__.py"
    networks:
      - agent_network

  ## Build from here https://github.com/a2aproject/a2a-inspector.git
  a2ainspector:
    image: a2a-inspector
    ports:
      - "6007:8080"
    networks:
      - agent_network

volumes:
  ollama_data:
    name: ollama_data

networks:
  agent_network:
    driver: bridge
